name: main 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python: [3.9, 3.11]
        exclude:
         - os: ubuntu-latest
           python-version: "3.10"

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: instalacja python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: x64

    - name: update pip
      run: |
        python -m pip install --upgrade pip

    - name: instalacja dependencies
      run: |
        python -m pip install flake8
    - name: instalacja dependencies2
      run: |
        python -m pip install unittest2

    - name: wyświetlenie wersji pythona
      run: |
        python --version

    - name: sprawdzenie stylu flake8
      run: |
        flake8 .

    - name: odpalenie unittest
      run: |
        python -m unittest discover -v
